""" This section stolen from Janus
set nocompatible      " Use vim, no vi defaults
set number            " Show line numbers
set ruler             " Show line and column number
syntax enable         " Turn on syntax highlighting allowing local overrides
set encoding=utf-8    " Set default encoding to UTF-8

set nowrap                        " don't wrap lines
set tabstop=2                     " a tab is two spaces
set shiftwidth=2                  " an autoindent (with <<) is two spaces
set expandtab                     " use spaces, not tabs
set list                          " Show invisible characters
set backspace=indent,eol,start    " backspace through everything in insert mode

if exists("g:enable_mvim_shift_arrow")
  let macvim_hig_shift_movement = 1 " mvim shift-arrow-keys
endif

" List chars
set listchars=""                  " Reset the listchars
set listchars=tab:\ \             " a tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.            " show trailing spaces as dots
set listchars+=extends:>          " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen
set listchars+=precedes:<         " The character to show in the last column when wrap is
                                  " off and the line continues beyond the left of the screen
set hlsearch    " highlight matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter
""" end stolen section

""load up the vundles
source ~/.vundlerc

""always show me the freaking status bar
set laststatus=2

"" no folding because it sucks
set nofoldenable

""use the system clipboard
""note to self: this is still totally broken in terminal
set clipboard=unnamed

""set my font size to be legible
""set guifont=Menlo:h16
""font is set in airline configs instead. see vundlerc

""muh colors
colors molokai

""ignore crap with ctrlP to make it usable
let g:ctrlp_custom_ignore = {
\ 'dir':  '\.git$\|\.yardoc\|node_modules\|public\|bower_components\|dist\|build\|log\|tmp$',
\ 'file': '\.so$\|\.dat$|\.DS_Store$'
\ }

"""my glorious mappings for extra laziness
"make reloading my config super easy, super dangerous
map <leader>r :source ~/.vimrc

"make commands easier to input
map ; :
"rebind ex mode to replay q macro
map Q @q

"reaching for esc is hard
imap kj <Esc>

""map ' to \ since i dont use it either
""i like having two keys bound to the same thing
map ' \
